import { Localization } from '../../../localization';

export interface DressLocalization extends Localization {
  getGenerate();
  getHeader();
  getClothes();
  getClothesByRoll(roll: number);
  //getBikerLeathers();
  //getBlueJeans();
  //getCorporateSuits();
  //getJumpsuits();
  //getMiniSkirts();
  //getHighFashion();
  //getCammos();
  //getNormalClothes();
  //getNude();
  //getBagLadyChic();
  getHairstyle();
  getHairstyleByRoll(roll: number);
  //getMohawk();
  //getLongRatty();
  //getShortSpiked();
  //getWild();
  //getBald();
  //getStriped();
  //getTinted();
  //getNeat();
  //getShort();
  //getLong();
  getAffectations();
  getAffectationsByRoll(roll: number);
  //getTatoos();
  //getMirrorshades();
  //getRitualScars();
  //getSpikedGloves();
  //getNoseRings();
  //getEarrings();
  //getLongFingernails();
  //getHeeledBoots();
  //getContactLenses();
  //getFingerlessGloves();
}
